# Generated by Django 5.0 on 2023-12-20 23:36

import datetime
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'), # this is the missing part
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(unique=True)),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("email", models.CharField(unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "User",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.UUIDField(db_column="user")),
                ("date", models.DateField(db_column="date")),
                (
                    "created",
                    models.DateField(db_column="created", default=datetime.date.today),
                ),
                (
                    "total",
                    models.DecimalField(
                        db_column="total", decimal_places=2, max_digits=13
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, db_column="description", null=True),
                ),
                (
                    "receipt",
                    models.ImageField(
                        blank=True, db_column="receipt", null=True, upload_to=""
                    ),
                ),
            ],
            options={
                "db_table": "Bill",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name", max_length=128)),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=2, max_digits=13
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        db_column="quantity", decimal_places=2, max_digits=13
                    ),
                ),
                ("note", models.TextField(blank=True, db_column="note", null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        db_column="bill",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.bill",
                    ),
                ),
            ],
            options={
                "db_table": "Position",
            },
        ),
    ]
