# Generated by Django 5.0 on 2024-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_add_bill_and_position_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="name",
            field=models.CharField(
                blank=True, db_column="name", max_length=100, null=True
            ),
        ),
        migrations.RunSQL("UPDATE public.\"Bill\" SET name = 'Rechnung #' || CAST(id AS VARCHAR);")
    ]
