# Generated by Django 5.0 on 2024-01-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_bill_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="name",
            field=models.CharField(db_column="name", max_length=100),
        ),
    ]
