# Generated by Django 5.0 on 2024-01-09 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_bill_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name")),
                ("user", models.UUIDField(db_column="user", null=True)),
                ("icon", models.ImageField(db_column="icon", null=True, upload_to="")),
            ],
            options={
                "db_table": "Group",
            },
        ),
        migrations.AddField(
            model_name="position",
            name="group",
            field=models.ForeignKey(
                db_column="group",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.group",
            ),
        ),
    ]
