# Generated by Django 5.0 on 2024-01-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_group_position_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="icon",
            field=models.ImageField(db_column="icon", null=True, upload_to="groups"),
        ),
        migrations.AlterField(
            model_name="position",
            name="bill",
            field=models.ForeignKey(
                db_column="bill",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="app.bill",
            ),
        ),
    ]
