# Generated by Django 5.0 on 2024-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_group_icon_alter_position_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
