# Generated by Django 5.0 on 2024-03-05 19:00

from django.db import migrations
from ..models.Group import Group

def forward_func(app, schema):
    # Daily Living expenses
    Group.objects.update_or_create(name="Groceries", user=None, icon=None)
    Group.objects.update_or_create(name="Dining out", user=None, icon=None)
    Group.objects.update_or_create(name="Utilities", user=None, icon=None)
    Group.objects.update_or_create(name="Transportation", user=None, icon=None)
    Group.objects.update_or_create(name="Housing", user=None, icon=None)
    
    # Health and Wellness
    Group.objects.update_or_create(name="Healthcare", user=None, icon=None)
    Group.objects.update_or_create(name="Fitnesss", user=None, icon=None)
    Group.objects.update_or_create(name="Personal Care", user=None, icon=None)
    
    # Leisure and Entertainment
    Group.objects.update_or_create(name="Entertainment", user=None, icon=None)
    Group.objects.update_or_create(name="Travel", user=None, icon=None)
    Group.objects.update_or_create(name="Gifts and Celebrations", user=None, icon=None)
    
    # Education and Development
    Group.objects.update_or_create(name="Education", user=None, icon=None)
    Group.objects.update_or_create(name="Childcare", user=None, icon=None)
    
    # Financial and Professional
    Group.objects.update_or_create(name="Investmens", user=None, icon=None)
    Group.objects.update_or_create(name="Professional Expenses", user=None, icon=None)
    Group.objects.update_or_create(name="Savings and Debt", user=None, icon=None)
    
    # Household and Maintenance
    Group.objects.update_or_create(name="Household Supplies", user=None, icon=None)
    Group.objects.update_or_create(name="Home Improvement", user=None, icon=None)
    
    # Miscallaneous
    Group.objects.update_or_create(name="Clothing and Accessories", user=None, icon=None)
    Group.objects.update_or_create(name="Pets", user=None, icon=None)
    
class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_bill_paid_alter_position_group"),
    ]

    operations = [
        migrations.RunPython(forward_func, None)
    ]
