# Generated by Django 5.0 on 2025-12-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_address_country_shop_bill_channel_alter_bill_receipt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("has_physical_stores", models.BooleanField(default=False)),
                ("default_channel", models.CharField(max_length=100)),
                (
                    "icon",
                    models.ImageField(db_column="icon", null=True, upload_to="brands"),
                ),
            ],
            options={
                "db_table": "Brand",
            },
        ),
        migrations.RemoveField(
            model_name="bill",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="shopaddress",
            name="shop",
        ),
        migrations.RemoveField(
            model_name="shopaddress",
            name="address",
        ),
        migrations.AddField(
            model_name="bill",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                db_column="fk_brand",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.brand",
            ),
        ),
        migrations.CreateModel(
            name="BrandAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        db_column="fk_address",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.address",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        db_column="fk_brand",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.brand",
                    ),
                ),
            ],
            options={
                "db_table": "Brand_Address",
            },
        ),
        migrations.AddField(
            model_name="brand",
            name="addresses",
            field=models.ManyToManyField(
                blank=True, through="app.BrandAddress", to="app.address"
            ),
        ),
        migrations.DeleteModel(
            name="Shop",
        ),
        migrations.DeleteModel(
            name="ShopAddress",
        ),
    ]
