# Generated by Django 5.0 on 2026-03-06 21:50

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_brand_remove_bill_shop_remove_shopaddress_shop_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="user",
            field=models.ForeignKey(
                db_column="user",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
