# Generated by Django 5.0 on 2026-06-18 21:03

from django.db import migrations

from app.models.Group import Group

def forward_func(app, schema):
    Group.objects.update_or_create(name="Electronics", user=None, icon=None)
    Group.objects.update_or_create(name="Furniture and Decor", user=None, icon=None)

class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_user_alter_bill_user_alter_group_user"),
    ]

    operations = [
        migrations.RunPython(forward_func, None)
    ]
