# Generated by Django 5.0 on 2026-06-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_add_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="price",
            field=models.DecimalField(
                db_column="price", decimal_places=3, max_digits=13
            ),
        ),
        migrations.AlterField(
            model_name="position",
            name="quantity",
            field=models.DecimalField(
                db_column="quantity", decimal_places=3, max_digits=13
            ),
        ),
    ]
