# Generated by Django 5.0 on 2026-07-19 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_position_price_alter_position_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrentPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_column="name")),
                ("start_date", models.DateField(db_column="start_date")),
                ("frequency", models.CharField(db_column="frequency")),
                ("interval", models.IntegerField(db_column="interval")),
                (
                    "brand",
                    models.ForeignKey(
                        db_column="fk_brand",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recurrent_payments",
                        to="app.brand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="fk_user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrent_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "RecurrentPayment",
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="recurrent_payment",
            field=models.ForeignKey(
                db_column="fk_recurrent_payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.recurrentpayment",
            ),
        ),
        migrations.CreateModel(
            name="RecurrentPaymentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        db_column="price", decimal_places=3, max_digits=13
                    ),
                ),
                ("valid_from", models.DateField(db_column="valid_from")),
                (
                    "valid_through",
                    models.DateField(db_column="valid_through", null=True),
                ),
                (
                    "recurrent_payment",
                    models.ForeignKey(
                        db_column="fk_recurrent_payment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="app.recurrentpayment",
                    ),
                ),
            ],
            options={
                "db_table": "RecurrentPaymentPrice",
            },
        ),
    ]
