version: "3.1"
services:
  app:
    image: "financewatcher-dev"
    build:
      dockerfile: .devcontainer/Dockerfile
      context: ..
    hostname: bjarne-ubuntu
    container_name: financewatcher-application
    ports:
      - 8000:8000
    env_file: .application.env
    volumes:
      - ..:/workspace:cached
    networks:
      - financewatcher
    depends_on:
      - database
  database:
    container_name: financewatcher-database
    image: "postgres:alpine3.16"
    ports:
      - 5434:5432
    env_file: .database.env
    volumes:
      - financewatcher-data:/var/lib/postgesql/data
    networks:
      - financewatcher
      - pgadmin

volumes:
  financewatcher-data:

networks:
  pgadmin:
    external: true
  financewatcher:
    external: true
